name: evl
sha1: 2f732be894234e71f68e2563f6b1e3958255b328
options:
  basename: evl
  target_path: disks/jp_bombom/EVL_REL.BIN
  base_path: ../..
  platform: psx
  compiler: PSYQ

  asm_path: asm/jp_bombom/evl
  src_path: src/evl
  asset_path: build/jp_bombom/psx/generated/assets/evl
  build_path: build

  ld_script_path: build/jp_bombom/psx/generated/evl.ld

  global_vram_start: 0x80000000
  global_vram_end: 0x80200000

  gp_value: 0x8014685C

  generate_asm_macros_files: False

  section_order: [".text", ".rodata", ".data", ".sdata", ".sbss", ".bss"]

  symbol_addrs_path:
    - config/jp_bombom/symbols.txt
    - config/jp_bombom/symbols_evl.txt

  undefined_funcs_auto_path: build/jp_bombom/psx/generated/undefined_funcs_auto_evl.txt
  undefined_syms_auto_path: build/jp_bombom/psx/generated/undefined_syms_auto_evl.txt

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

  migrate_rodata_to_functions: False

  create_data_pads: False

  use_gp_rel_macro: True

  asm_data_macro: dlabel_section
  asm_data_end_label: enddlabel_section

  symbol_name_format: $VRAM_evl
  symbol_name_format_no_rom: $VRAM_evl

segments:
  - name: header
    type: rodata
    start: 0x0
    vram: 0x80060000
    align: 4
    subalign: 4

  - name: evl
    type: code
    start: 0x40
    vram: 0x80060040
    align: 4
    subalign: 4
    subsegments:
      - [0x40, c, evl]
      - [0x5730, .rodata, evl]
      - [0x5744, .data, evl]
      - [0x5784, .data, evl_bss_jp_bombom]

  - [0xA84C]
