name: shop
sha1: 486ed06dd960230ddd63889ab865c72eac69b5ac
options:
  basename: shop
  target_path: disks/jp_bombom/SHOP_REL.BIN
  base_path: ../..
  platform: psx
  compiler: PSYQ

  asm_path: asm/jp_bombom/shop
  src_path: src/shop
  asset_path: build/jp_bombom/psx/generated/assets/shop
  build_path: build

  ld_script_path: build/jp_bombom/psx/generated/shop.ld

  global_vram_start: 0x80000000
  global_vram_end: 0x80200000

  gp_value: 0x8014685C

  generate_asm_macros_files: False

  section_order: [".text", ".rodata", ".data", ".sdata", ".sbss", ".bss"]

  symbol_addrs_path:
    - config/jp_bombom/symbols.txt
    - config/jp_bombom/symbols_shop.txt

  undefined_funcs_auto_path: build/jp_bombom/psx/generated/undefined_funcs_auto_shop.txt
  undefined_syms_auto_path: build/jp_bombom/psx/generated/undefined_syms_auto_shop.txt

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

  migrate_rodata_to_functions: False

  create_data_pads: False

  use_gp_rel_macro: True

  symbol_name_format: $VRAM_shop
  symbol_name_format_no_rom: $VRAM_shop

segments:
  - name: header
    type: rodata
    start: 0x0
    vram: 0x80080800
    align: 4
    subalign: 4

  - name: shop
    type: code
    start: 0x40
    vram: 0x80080840
    align: 4
    subalign: 4
    subsegments:
      - [0x40, c, script_menu]
      - [0x7860, .rodata, script_menu]
      - [0x79F8, .data, script_menu]

  - [0x7E0C]
