name: vs
sha1: 61532097cab7ea85e8fffb680eac056b3c1c7c6c
options:
  basename: vs
  target_path: disks/jp_bombom/VS_REL.BIN
  base_path: ../..
  platform: psx
  compiler: PSYQ

  asm_path: asm/jp_bombom/vs
  src_path: src/vs
  asset_path: build/jp_bombom/psx/generated/assets/vs
  build_path: build

  ld_script_path: build/jp_bombom/psx/generated/vs.ld

  global_vram_start: 0x80000000
  global_vram_end: 0x80200000

  gp_value: 0x8014685C

  generate_asm_macros_files: False

  section_order: [".text", ".rodata", ".data", ".sdata", ".sbss", ".bss"]

  symbol_addrs_path:
    - config/jp_bombom/symbols.txt
    - config/jp_bombom/symbols_vs.txt
  reloc_addrs_path:
    - config/jp_bombom/relocs_vs.txt

  undefined_funcs_auto_path: build/jp_bombom/psx/generated/undefined_funcs_auto_vs.txt
  undefined_syms_auto_path: build/jp_bombom/psx/generated/undefined_syms_auto_vs.txt

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

  migrate_rodata_to_functions: False

  create_data_pads: False

  use_gp_rel_macro: True

  symbol_name_format: $VRAM_vs
  symbol_name_format_no_rom: $VRAM_vs

segments:
  - name: texture
    type: rodata
    start: 0x0
    vram: 0x80052AE0
    align: 4
    subalign: 4

  - name: model_0
    type: rodata
    start: 0xD20
    vram: 0x80053800
    align: 4
    subalign: 4

  - name: model_1
    type: rodata
    start: 0x1D58
    vram: 0x80054838
    align: 4
    subalign: 4

  - name: model_2
    type: rodata
    start: 0x2220
    vram: 0x80054D00
    align: 4
    subalign: 4

  - name: model_3
    type: rodata
    start: 0x2848
    vram: 0x80055328
    align: 4
    subalign: 4

  - name: header
    type: rodata
    start: 0x4188
    vram: 0x80056C68
    align: 4
    subalign: 4

  - name: vs
    type: code
    start: 0x41C8
    vram: 0x80056CA8
    align: 4
    subalign: 4
    subsegments:
      - [0x41C8, c, vs_demo]
      - [0x5870, c, vs_select]
      - [0x9440, c, vs_scene]
      - [0xC174, c, vs_intro]
      - [0xDA24, c, vs_camera]
      - [0x1052C, c, vs_combat]
      - [0x17324, c, vs_main]
      - [0x1CC9C, c, vs_hud]
      - [0x22120, c, vs_effect]
      - [0x32C1C, .rodata, vs_scene]
      - [0x32C34, .rodata, vs_intro]
      - [0x32C50, .rodata, vs_camera]
      - [0x32C7C, .rodata, vs_combat]
      - [0x32C9C, .rodata, vs_hud]
      - [0x32CC4, .data, vs_demo]
      - [0x32DE0, .data, vs_select]
      - [0x3305C, .data, vs_scene]
      - [0x33C7C, .data, vs_intro]
      - [0x33CA8, .data, vs_camera]
      - [0x33D8C, .data, vs_combat]
      - [0x33D98, .data, vs_main]
      - [0x33E7C, .data, vs_hud]
      - [0x341EC, .data, vs_effect]
      - [0x34D48, .data, vs_bss_jp_bombom]

  - [0x369C8]
