name: doo2
sha1: 87e73d09b01b93276a4ba4729aed6647a8a79ccf
options:
  basename: doo2
  target_path: disks/eu/DOO2_REL.BIN
  base_path: ../..
  platform: psx
  compiler: PSYQ

  asm_path: asm/eu/doo2
  src_path: src/doo2
  asset_path: build/eu/psx/generated/assets/doo2
  build_path: build

  ld_script_path: build/eu/psx/generated/doo2.ld

  global_vram_start: 0x80000000
  global_vram_end: 0x80200000

  gp_value: 0x80142BF4

  generate_asm_macros_files: False

  section_order: [".text", ".rodata", ".data", ".sdata", ".sbss", ".bss"]

  symbol_addrs_path:
    - config/eu/symbols.txt
    - config/eu/symbols_doo2.txt

  undefined_funcs_auto_path: build/eu/psx/generated/undefined_funcs_auto_doo2.txt
  undefined_syms_auto_path: build/eu/psx/generated/undefined_syms_auto_doo2.txt

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

  migrate_rodata_to_functions: False

  create_data_pads: False

  use_gp_rel_macro: True

  asm_data_macro: dlabel_section
  asm_data_end_label: enddlabel_section

  symbol_name_format: $VRAM_doo2
  symbol_name_format_no_rom: $VRAM_doo2

segments:
  - name: header
    type: rodata
    start: 0x0
    vram: 0x80070000
    align: 4
    subalign: 4

  - name: doo2
    type: code
    start: 0x40
    vram: 0x80070040
    align: 4
    subalign: 4
    subsegments:
      - [0x40, c, doo2]
      - [0x2788, .data, doo2]
      - [0x27EC, .data, doo2_bss_eu]

  - [0xC3F4]
