name: kar
sha1: a15839694d5feb60fd73d0ca174a1c2838a0548c
options:
  basename: kar
  target_path: disks/eu/KAR_REL.BIN
  base_path: ../..
  platform: psx
  compiler: PSYQ

  asm_path: asm/eu/kar
  src_path: src/kar
  asset_path: build/eu/psx/generated/assets/kar
  build_path: build

  ld_script_path: build/eu/psx/generated/kar.ld

  global_vram_start: 0x80000000
  global_vram_end: 0x80200000

  gp_value: 0x80142BF4

  generate_asm_macros_files: False

  section_order: [".text", ".rodata", ".data", ".sdata", ".sbss", ".bss"]

  symbol_addrs_path:
    - config/eu/symbols.txt
    - config/eu/symbols_kar.txt

  undefined_funcs_auto_path: build/eu/psx/generated/undefined_funcs_auto_kar.txt
  undefined_syms_auto_path: build/eu/psx/generated/undefined_syms_auto_kar.txt

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

  migrate_rodata_to_functions: False

  create_data_pads: False

  use_gp_rel_macro: True

  symbol_name_format: $VRAM_kar
  symbol_name_format_no_rom: $VRAM_kar

segments:
  - name: header
    type: rodata
    start: 0x0
    vram: 0x80053800
    align: 4
    subalign: 4

  - name: kar
    type: code
    start: 0x40
    vram: 0x80053840
    align: 4
    subalign: 4
    subsegments:
      - [0x40, asm, kar]
      - [0x9818, data, kar]

  - [0x12808]
