name: main
sha1: a805aad8bb6b2a12b145bd2172697aff7a28d25e
options:
  basename: main
  target_path: disks/eu/SLES_029.14
  base_path: ../..
  platform: psx
  compiler: PSYQ

  asm_path: asm/eu/main
  src_path: src/main
  asset_path: build/eu/psx/generated/assets/main
  build_path: build

  ld_script_path: build/eu/psx/generated/main.ld

  global_vram_start: 0x80000000
  global_vram_end: 0x80200000

  gp_value: 0x80142BF4

  generate_asm_macros_files: False

  section_order: [".text", ".rodata", ".data", ".sdata", ".sbss", ".bss"]

  symbol_addrs_path:
    - config/eu/symbols.txt
    - config/eu/symbols_main.txt
  reloc_addrs_path:
    - config/eu/relocs_main.txt

  undefined_funcs_auto_path: build/eu/psx/generated/undefined_funcs_auto_main.txt
  undefined_syms_auto_path: build/eu/psx/generated/undefined_syms_auto_main.txt

  ld_gp_expression: main_SDATA_START + 0x8000

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

  migrate_rodata_to_functions: False

  create_data_pads: False

  use_gp_rel_macro: True

segments:
  - name: header
    type: data
    start: 0x0
    vram: 0x80090000
    align: 4
    subalign: 4

  - name: main
    type: code
    start: 0x800
    vram: 0x80090800
    align: 4
    subalign: 4
    subsegments:
      - [0x800, asm, psyq/libapi]
      - [0x12D4, asm, psyq/libc]
      - [0x1CFC, asm, psyq/libetc]
      - [0x29C4, asm, psyq/libgpu]
      - [0x5894, asm, psyq/libgs]
      - [0x927C, asm, psyq/libgte]
      - [0xF714, c, model]
      - [0x12980, c, world_object]
      - [0x12E08, c, file]
      - [0x13440, c, math]
      - [0x137C4, c, graphics]
      - [0x13FD0, c, font]
      - [0x14704, c, drop_shadow]
      - [0x14B20, c, _psstart]
      - [0x14C68, c, partner_impl]
      - [0x1AF34, c, tamer]
      - [0x1F024, c, fade]
      - [0x1F518, c, aabb]
      - [0x1FA64, c, efe]
      - [0x23150, asm, psyq/libcd]
      - [0x272D0, c, overworld]
      - [0x2CA18, c, game_menu]
      - [0x374FC, c, map_collision]
      - [0x37E08, c, particle]
      - [0x386B4, c, anim]
      - [0x39CA8, c, ui]
      - [0x3B464, c, item]
      - [0x3DBE4, c, sound]
      - [0x3EC10, asm, psyq/libspu]
      - [0x41DF4, asm, psyq/libsnd]
      - [0x4ABD0, c, map]
      - [0x53900, c, inventory]
      - [0x564B8, c, clock]
      - [0x56FE4, c, partner]
      - [0x597B8, c, script_interp]
      - [0x5EF98, c, entity_text]
      - [0x5F780, c, script_textbox]
      - [0x62360, c, script_value]
      - [0x62DEC, c, map_object]
      - [0x65E5C, c, script_common]
      - [0x6C908, c, evolution]
      - [0x6DE58, c, file_queue]
      - [0x6E548, c, line]
      - [0x6E98C, c, vecmath]
      - [0x6FF68, c, rng]
      - [0x70030, c, fish]
      - [0x70480, c, utils]
      - [0x70E30, c, utils2]
      - [0x72904, c, tournament]
      - [0x72F18, c, evl]
      - [0x731FC, c, btl]
      - [0x74F8C, c, kar]
      - [0x74FD4, c, efe_table]
      - [0x750E0, c, sound_async]
      - [0x75A80, asm, psyq/libpress]
      - [0x76408, asm, psyq/libds]
      - [0x76458, c, butterfly]
      - [0x76830, c, main_menu]
      - [0x7EB74, asm, psyq/libmcrd]
      - [0x81D60, c, bubble]
      - [0x8297C, c, battle_ui]
      - [0x84974, c, main]
      - [0x8751C, c, battle_tick]
      - [0x880C0, c, new_game]
      - [0x883E4, c, buff_model]
      - [0x8861C, c, effect_common]
      - [0x89E88, bin, rts_info, discard:True]
      - [0x89F38, rodata, psyq/libc]
      - [0x8A018, rodata, psyq/libetc]
      - [0x8A0C8, rodata, psyq/libgpu]
      - [0x8A318, rodata, psyq/libgs]
      - [0x8A538, .rodata, tamer]
      - [0x8A5E4, .rodata, efe]
      - [0x8A600, rodata, psyq/libcd]
      - [0x8AAE0, .rodata, overworld]
      - [0x8AB44, .rodata, game_menu]
      - [0x8AC24, .rodata, item]
      - [0x8AC6C, rodata, psyq/libspu]
      - [0x8AD3C, rodata, psyq/libsnd]
      - [0x8ADCC, .rodata, inventory]
      - [0x8AE0C, .rodata, partner]
      - [0x8AEE8, .rodata, script_interp]
      - [0x8B320, .rodata, script_textbox]
      - [0x8B378, .rodata, script_value]
      - [0x8B3D4, .rodata, map_object]
      - [0x8B458, .rodata, script_common]
      - [0x8B4B4, .rodata, vecmath]
      - [0x8B5B4, rodata, psyq/libpress]
      - [0x8B604, .rodata, main_menu]
      - [0x8B6D4, rodata, psyq/libmcrd]
      - [0x8B904, .rodata, battle_ui]
      - [0x8B91C, .rodata, main]
      - [0x8B938, data, psyq/libapi]
      - [0x8B978, data, psyq/libc]
      - [0x8B988, data, psyq/libetc]
      - [0x8CAB8, data, psyq/libgpu]
      - [0x8CC50, data, psyq/libgte]
      - [0x920E4, .data, model]
      - [0x93404, .data, file_table_eu]
      - [0x9882C, .data, graphics]
      - [0x98848, .data, font]
      - [0x99A08, .data, partner_impl]
      - [0x9A1D8, .data, tamer]
      - [0x9A308, .data, toilet_data]
      - [0x9A358, .data, door_mapdata]
      - [0x9A868, .data, efe]
      - [0x9A944, data, psyq/libcd]
      - [0x9AD9C, .data, game_menu]
      - [0x9C7D4, .data, particle]
      - [0x9C858, .data, ui]
      - [0x9C8B0, .data, item]
      - [0xA1304, .data, sound]
      - [0xA14C8, data, psyq/libspu]
      - [0xA1DB0, data, psyq/libsnd]
      - [0xA1F18, .data, map]
      - [0xA38D0, .data, inventory]
      - [0xA395C, .data, clock]
      - [0xA398C, .data, script_interp]
      - [0xA39D4, .data, entity_text]
      - [0xA39EC, .data, script_value]
      - [0xA3A98, .data, map_object]
      - [0xA3C44, .data, script_common]
      - [0xA4A30, .data, evolution]
      - [0xA575C, .data, utils]
      - [0xA57B4, .data, utils2]
      - [0xA5920, .data, tournament]
      - [0xA592C, .data, btl]
      - [0xA5988, .data, efe_table]
      - [0xA59C8, .data, sound_async]
      - [0xA5A24, data, psyq/libpress]
      - [0xA6994, .data, butterfly]
      - [0xA69B8, .data, main_menu]
      - [0xA7D74, data, psyq/libmcrd]
      - [0xA7DA4, .data, bubble]
      - [0xA807C, .data, battle_ui]
      - [0xA8094, .data, main]
      - [0xAA504, .data, effect_common]
      - [0xAABF4, .sdata, model]
      - [0xAB1C4, .sdata, file_table_eu]
      - [0xAB2C4, .sdata, font]
      - [0xAB2C8, .sdata, partner_impl]
      - [0xAB2D0, .sdata, tamer]
      - [0xAB2F8, .sdata, efe]
      - [0xAB308, .sdata, overworld]
      - [0xAB318, .sdata, game_menu]
      - [0xAB3C0, .sdata, ui]
      - [0xAB3E8, .sdata, item]
      - [0xAB404, .sdata, sound]
      - [0xAB430, .sdata, map]
      - [0xAB454, .sdata, inventory]
      - [0xAB46C, .sdata, clock]
      - [0xAB47C, .sdata, script_interp]
      - [0xAB480, .sdata, entity_text]
      - [0xAB488, .sdata, script_value]
      - [0xAB490, .sdata, map_object]
      - [0xAB4CC, .sdata, script_common]
      - [0xAB588, .sdata, file_queue]
      - [0xAB58C, .sdata, rng]
      - [0xAB590, .sdata, efe_table]
      - [0xAB594, .sdata, sound_async]
      - [0xAB5B4, .sdata, main_menu]
      - [0xAB670, .sdata, bubble]
      - [0xAB6E4, .sdata, battle_ui]
      - [0xAB6F0, .sdata, main]
      - [0xAB704, .sdata, btl/battle_setup]
      - [0xAB714, .sdata, btl/battle_main]
      - [0xAB728, .sdata, btl/command_shout]
      - [0xAB734, .sdata, btl/command_menu]
      - [0xAB74C, .sdata, btl/battle_hud]
      - [0xAB790, .sdata, btl/battle_effect]
      - [0xAB810, .sdata, std/std_setup]
      - [0xAB814, .sdata, std/std_main]
      - [0xAB8B8, .sdata, std/std_hud]
      - [0xAB8DC, .sdata, std/std_effect]
      - [0xAB950, .sdata, fish/fish]
      - [0xABA0C, .sdata, evl/evl]
      - [0xABA30, .sdata, kar/kar]
      - [0xABA80, .sdata, vs/vs_select]
      - [0xABAAC, .sdata, vs/vs_scene]
      - [0xABABC, .sdata, vs/vs_intro]
      - [0xABAD4, .sdata, vs/vs_camera]
      - [0xABB2C, .sdata, vs/vs_combat]
      - [0xABB3C, .sdata, vs/vs_main]
      - [0xABB54, .sdata, vs/vs_hud]
      - [0xABB88, .sdata, vs/vs_effect]
      - [0xABBFC, .sdata, doo2/doo2]
      - [0xABC18, .sdata, dooa/dooa]
      - [0xABC2C, .sdata, trn/trn_reward]
      - [0xABC34, .sdata, trn/trn_hud]
      - [0xABC3C, .sdata, trn/trn_slots]
      - [0xABC54, .sdata, shop/script_menu]
      - [0xABCAC, .sdata, trn2/trn2_hud]
      - [0xABCB4, .sdata, trn2/trn2_slots]
      - [0xABCCC, .sdata, murd/murd]
      - [0xABCE8, .sdata, endi/endi]
      - [0xABCF4, .sdata, eab/eab]

  - [0xABD18]
