name: mov
sha1: a6bef17e9a03232afe371c7d80a85d4c0d3e072d
options:
  basename: mov
  target_path: disks/jp/MOV_REL.BIN
  base_path: ../..
  platform: psx
  compiler: PSYQ

  asm_path: asm/jp/mov
  src_path: src/mov
  asset_path: build/jp/psx/generated/assets/mov
  build_path: build

  ld_script_path: build/jp/psx/generated/mov.ld

  global_vram_start: 0x80000000
  global_vram_end: 0x80200000

  gp_value: 0x80144E0C

  generate_asm_macros_files: False

  section_order: [".text", ".rodata", ".data", ".sdata", ".sbss", ".bss"]

  symbol_addrs_path:
    - config/jp/symbols.txt
    - config/jp/symbols_mov.txt

  undefined_funcs_auto_path: build/jp/psx/generated/undefined_funcs_auto_mov.txt
  undefined_syms_auto_path: build/jp/psx/generated/undefined_syms_auto_mov.txt

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

  migrate_rodata_to_functions: False

  create_data_pads: False

  use_gp_rel_macro: True

  symbol_name_format: $VRAM_mov
  symbol_name_format_no_rom: $VRAM_mov

segments:
  - name: header
    type: rodata
    start: 0x0
    vram: 0x80010000
    align: 4
    subalign: 4

  - name: mov
    type: code
    start: 0x40
    vram: 0x80010040
    align: 4
    subalign: 4
    subsegments:
      - [0x40, c, mov]
      - [0xB70, .data, mov]
      - [0xC10, .data, mov_bss_jp]

  - [0x7364C]
