name: vs
sha1: 0f7d865db632468381e8022b1c59f98133cf8067
options:
  basename: vs
  target_path: disks/jp/VS_REL.BIN
  base_path: ../..
  platform: psx
  compiler: PSYQ

  asm_path: asm/jp/vs
  src_path: src/vs
  asset_path: build/jp/psx/generated/assets/vs
  build_path: build

  ld_script_path: build/jp/psx/generated/vs.ld

  global_vram_start: 0x80000000
  global_vram_end: 0x80200000

  gp_value: 0x80144E0C

  generate_asm_macros_files: False

  section_order: [".text", ".rodata", ".data", ".sdata", ".sbss", ".bss"]

  symbol_addrs_path:
    - config/jp/symbols.txt
    - config/jp/symbols_vs.txt

  undefined_funcs_auto_path: build/jp/psx/generated/undefined_funcs_auto_vs.txt
  undefined_syms_auto_path: build/jp/psx/generated/undefined_syms_auto_vs.txt

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

  migrate_rodata_to_functions: False

  create_data_pads: False

  use_gp_rel_macro: True

  symbol_name_format: $VRAM_vs
  symbol_name_format_no_rom: $VRAM_vs

segments:
  - name: texture
    type: rodata
    start: 0x0
    vram: 0x80052AE0
    align: 4
    subalign: 4

  - name: model_0
    type: rodata
    start: 0xD20
    vram: 0x80053800
    align: 4
    subalign: 4

  - name: model_1
    type: rodata
    start: 0x1D58
    vram: 0x80054838
    align: 4
    subalign: 4

  - name: model_2
    type: rodata
    start: 0x2220
    vram: 0x80054D00
    align: 4
    subalign: 4

  - name: model_3
    type: rodata
    start: 0x2848
    vram: 0x80055328
    align: 4
    subalign: 4

  - name: header
    type: rodata
    start: 0x4188
    vram: 0x80056C68
    align: 4
    subalign: 4

  - name: vs
    type: code
    start: 0x41C8
    vram: 0x80056CA8
    align: 4
    subalign: 4
    subsegments:
      - [0x41C8, asm, vs]
      - [0xAA44, c, vs_intro]
      - [0xC2F4, asm]
      - [0x14B90, c, vs_main]
      - [0x1A508, c, vs_hud]
      - [0x1F8FC, asm]
      - [0x3050C, data, vs]
      - [0x30524, .rodata, vs_intro]
      - [0x30540, data]
      - [0x3058C, .rodata, vs_hud]
      - [0x305B4, data]
      - [0x31450, .data, vs_intro]
      - [0x3147C, data]
      - [0x3156C, .data, vs_main]
      - [0x31650, .data, vs_hud]
      - [0x319C0, data]

  - [0x3417C]
