name: shop
sha1: df99fa740b6b8bd7847dbd5c443e6d478a474bcf
options:
  basename: shop
  target_path: disks/us/SHOP_REL.BIN
  base_path: ..
  platform: psx
  compiler: PSYQ

  asm_path: asm/shop
  src_path: src/shop
  build_path: build

  ld_script_path: build/generated/shop.ld

  global_vram_start: 0x80000000
  global_vram_end: 0x80200000

  find_file_boundaries: True
  gp_value: 0x8013BB2C

  generate_asm_macros_files: False

  section_order: [".text", ".rodata", ".data", ".sdata", ".sbss", ".bss"]

  symbol_addrs_path:
    - config/symbols.txt
    - config/symbols_shop.txt
  reloc_addrs_path:
    - config/relocs_shop.txt

  undefined_funcs_auto_path: build/generated/undefined_funcs_auto_shop.txt
  undefined_syms_auto_path: build/generated/undefined_syms_auto_shop.txt

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

  use_gp_rel_macro: True

segments:
  - name: header
    type: rodata
    start: 0x0
    vram: 0x80080800
    align: 4
    subalign: 4

  - name: shop
    type: code
    start: 0x40
    vram: 0x80080840
    align: 4
    subalign: 4
    subsegments:
      - [0x40, asm]
      - [0x7860, data]

  - [0x7E10]
