name: vs
sha1: ff25808371c7db2a67da02adc708026cd9844df7
options:
  basename: vs
  target_path: disks/us/VS_REL.BIN
  base_path: ..
  platform: psx
  compiler: PSYQ

  asm_path: asm/vs
  src_path: src/vs
  build_path: build

  ld_script_path: build/generated/vs.ld

  global_vram_start: 0x80000000
  global_vram_end: 0x80200000

  find_file_boundaries: True
  gp_value: 0x8013BB2C

  generate_asm_macros_files: False

  section_order: [".text", ".rodata", ".data", ".sdata", ".sbss", ".bss"]

  symbol_addrs_path:
    - config/symbols.txt
    - config/symbols_vs.txt
  reloc_addrs_path:
    - config/relocs_vs.txt

  undefined_funcs_auto_path: build/generated/undefined_funcs_auto_vs.txt
  undefined_syms_auto_path: build/generated/undefined_syms_auto_vs.txt

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

  use_gp_rel_macro: True

segments:
  - name: texture
    type: rodata
    start: 0x0
    vram: 0x80052AE0
    align: 4
    subalign: 4

  - name: model_0
    type: rodata
    start: 0xD20
    vram: 0x80053800
    align: 4
    subalign: 4

  - name: model_1
    type: rodata
    start: 0x1D58
    vram: 0x80054838
    align: 4
    subalign: 4

  - name: model_2
    type: rodata
    start: 0x2220
    vram: 0x80054D00
    align: 4
    subalign: 4

  - name: model_3
    type: rodata
    start: 0x2848
    vram: 0x80055328
    align: 4
    subalign: 4

  - name: header
    type: rodata
    start: 0x4188
    vram: 0x80056C68
    align: 4
    subalign: 4

  - name: vs
    type: code
    start: 0x41C8
    vram: 0x80056CA8
    align: 4
    subalign: 4
    subsegments:
      - [0x41C8, asm]
      - [0x1CEDC, data]

  - [0x20788]
