
typedef unsigned char u_char;
typedef unsigned short u_short;
typedef unsigned int u_int;
typedef unsigned long u_long;
typedef unsigned short ushort;
typedef unsigned int uint;
typedef unsigned long ulong;
typedef struct _physadr
{
  int r[1];
} *physadr;
typedef struct label_t
{
  int val[12];
} label_t;
typedef struct _quad
{
  long val[2];
} quad;
typedef long daddr_t;
typedef char *caddr_t;
typedef long *qaddr_t;
typedef u_long ino_t;
typedef long swblk_t;
typedef unsigned int size_t;
typedef long time_t;
typedef short dev_t;
typedef long off_t;
typedef u_short uid_t;
typedef u_short gid_t;
extern int PadIdentifier;
int CheckCallback(void);
void PadInit(int mode);
int ResetCallback(void);
int RestartCallback(void);
int StopCallback(void);
int VSync(int mode);
int VSyncCallback(void (*f)());
long GetVideoMode(void);
long SetVideoMode(long mode);
u_long PadRead(int id);
void PadStop(void);
typedef struct VabHdr
{
  long form;
  long ver;
  long id;
  unsigned long fsize;
  unsigned short reserved0;
  unsigned short ps;
  unsigned short ts;
  unsigned short vs;
  unsigned char mvol;
  unsigned char pan;
  unsigned char attr1;
  unsigned char attr2;
  unsigned long reserved1;
} VabHdr;
typedef struct ProgAtr
{
  unsigned char tones;
  unsigned char mvol;
  unsigned char prior;
  unsigned char mode;
  unsigned char mpan;
  char reserved0;
  short attr;
  unsigned long reserved1;
  unsigned long reserved2;
} ProgAtr;
typedef struct VagAtr
{
  unsigned char prior;
  unsigned char mode;
  unsigned char vol;
  unsigned char pan;
  unsigned char center;
  unsigned char shift;
  unsigned char min;
  unsigned char max;
  unsigned char vibW;
  unsigned char vibT;
  unsigned char porW;
  unsigned char porT;
  unsigned char pbmin;
  unsigned char pbmax;
  unsigned char reserved1;
  unsigned char reserved2;
  unsigned short adsr1;
  unsigned short adsr2;
  short prog;
  short vag;
  short reserved[4];
} VagAtr;
typedef struct 
{
  unsigned short left;
  unsigned short right;
} SndVolume;
typedef struct SndVolume2
{
  short left;
  short right;
} SndVolume2;
typedef struct SndRegisterAttr
{
  SndVolume2 volume;
  short pitch;
  short mask;
  short addr;
  short adsr1;
  short adsr2;
} SndRegisterAttr;
typedef struct SndVoiceStats
{
  short vagId;
  short vabId;
  unsigned short pitch;
  short note;
  short tone;
  short prog_num;
  short prog_actual;
  short vol;
  short pan;
} SndVoiceStats;
typedef void (*SsMarkCallbackProc)(short, short, short);
extern short SsVabOpenHead(unsigned char *, short);
extern short SsVabOpenHeadSticky(unsigned char *, short, unsigned long);
extern short SsVabTransBody(unsigned char *, short);
extern short SsVabTransBodyPartly(unsigned char *, unsigned long, short);
extern short SsVabTransfer(unsigned char *, unsigned char *, short, short);
extern short SsVabTransCompleted(short);
extern void SsVabClose(short);
extern void SsInit(void);
extern void SsInitHot(void);
extern void SsSetTableSize(char *, short, short);
extern void SsSetTickMode(long);
extern int SsSetTickCallback(void (*cb)());
extern void SsStart(void);
extern void SsStart2(void);
extern void SsEnd(void);
extern void SsQuit(void);
extern void SsSeqCalledTbyT(void);
extern short SsSeqOpen(unsigned long *, short);
extern void SsSeqPlay(short, char, short);
extern void SsSeqPause(short);
extern void SsSeqReplay(short);
extern void SsSeqStop(short);
extern void SsSeqSetVol(short, short, short);
extern void SsSeqSetNext(short, short);
extern void SsSeqSetCrescendo(short, short, long);
extern void SsSeqSetDecrescendo(short, short, long);
extern void SsSeqSetAccelerando(short, long, long);
extern void SsSeqSetRitardando(short, long, long);
extern void SsSeqClose(short);
extern short SsSepOpen(unsigned long *, short, short);
extern void SsSepPlay(short, short, char, short);
extern void SsSepPause(short, short);
extern void SsSepReplay(short, short);
extern void SsSepStop(short, short);
extern void SsSepSetVol(short, short, short, short);
extern void SsSepSetCrescendo(short, short, short, long);
extern void SsSepSetDecrescendo(short, short, short, long);
extern void SsSepSetAccelerando(short, short, long, long);
extern void SsSepSetRitardando(short, short, long, long);
extern void SsSepClose(short);
extern long SsVoKeyOn(long, long, unsigned short, unsigned short);
extern long SsVoKeyOff(long, long);
extern void SsSetMVol(short, short);
extern void SsGetMVol(SndVolume *);
extern void SsSetRVol(short, short);
extern void SsGetRVol(SndVolume *);
extern void SsSetMute(char);
extern char SsGetMute(void);
extern void SsSetSerialAttr(char, char, char);
extern char SsGetSerialAttr(char, char);
extern void SsSetSerialVol(char, short, short);
extern void SsGetSerialVol(char, SndVolume *);
extern void SsSetNck(short);
extern short SsGetNck(void);
extern void SsSetNoiseOn(short, short);
extern void SsSetNoiseOff(void);
extern void SsSetMono(void);
extern void SsSetStereo(void);
extern void SsSetTempo(short, short, short);
extern void SsSetLoop(short, short, short);
extern short SsIsEos(short, short);
extern void SsPlayBack(short, short, short);
extern void SsSetMarkCallback(short, short, SsMarkCallbackProc);
extern char SsSetReservedVoice(char);
extern short SsUtKeyOn(short, short, short, short, short, short, short);
extern short SsUtKeyOff(short, short, short, short, short);
extern short SsUtKeyOnV(short voice, short vabId, short prog, short tone, short note, short fine, short voll, short volr);
extern short SsUtKeyOffV(short voice);
extern short SsUtPitchBend(short, short, short, short, short);
extern short SsUtChangePitch(short, short, short, short, short, short, short);
extern short SsUtChangeADSR(short, short, short, short, unsigned short, unsigned short);
extern short SsUtSetVabHdr(short, VabHdr *);
extern short SsUtGetVabHdr(short, VabHdr *);
extern short SsUtSetProgAtr(short, short, ProgAtr *);
extern short SsUtGetProgAtr(short, short, ProgAtr *);
extern short SsUtSetVagAtr(short, short, short, VagAtr *);
extern short SsUtGetVagAtr(short, short, short, VagAtr *);
extern short SsUtSetDetVVol(short, short, short);
extern short SsUtGetDetVVol(short, short *, short *);
extern short SsUtSetVVol(short, short, short);
extern short SsUtGetVVol(short, short *, short *);
extern short SsUtAutoVol(short, short, short, short);
extern short SsUtAutoPan(short, short, short, short);
extern void SsUtReverbOn(void);
extern void SsUtReverbOff(void);
extern short SsUtSetReverbType(short);
extern short SsUtGetReverbType(void);
extern void SsUtSetReverbDepth(short, short);
extern void SsUtSetReverbFeedback(short);
extern void SsUtSetReverbDelay(short);
extern void SsUtAllKeyOff(short);
extern void SsSetAutoKeyOffMode(short mode);
extern void SsUtFlush(void);
extern short SsVabFakeHead(unsigned char *, short, unsigned long);
extern short SsVabFakeBody(short);
extern unsigned long SsUtGetVBaddrInSB(short);
extern long SsUtGetVagAddr(short vabId, short vagId);
extern unsigned long SsUtGetVagAddrFromTone(short vabId, short progId, short toneId);
extern void SsSetNext(short, short, short, short);
extern void SsSeqGetVol(short, short, short *, short *);
extern void SsChannelMute(short, short, long);
extern short SsSeqOpenJ(unsigned long *, short);
extern short SsSepOpenJ(unsigned long *, short, short);
extern unsigned char *SsGetCurrentPoint(short, short);
extern long SsGetChannelMute(short, short);
extern void SsSetVoiceMask(unsigned long);
extern unsigned long SsGetVoiceMask(void);
extern void SsQueueRegisters(long, SndRegisterAttr *);
extern void SsQueueKeyOn(long);
extern void SsQueueReverb(long, long);
extern short SsGetActualProgFromProg(short, short);
extern void SsSetVoiceSettings(long, SndVoiceStats *);
extern unsigned short SsPitchFromNote(short, short, unsigned char, unsigned char);
extern short SsVoiceCheck(long, long, short);
extern char SsBlockVoiceAllocation(void);
extern char SsUnBlockVoiceAllocation(void);
extern long SsAllocateVoices(unsigned char, unsigned char);
typedef struct 
{
  void (*noteon)();
  void (*programchange)();
  void (*pitchbend)();
  void (*metaevent)();
  void (*control[13])();
  void (*ccentry[20])();
} _SsFCALL;
extern void _SsNoteOn(short, short, unsigned char, unsigned char);
extern void _SsSetProgramChange(short, short, unsigned char);
extern void _SsGetMetaEvent(short, short, unsigned char);
extern void _SsSetPitchBend(short, short);
extern void _SsSetControlChange(short, short, unsigned char);
extern void _SsContBankChange(short, short);
extern void _SsContDataEntry(short, short, unsigned char);
extern void _SsContMainVol(short, short, unsigned char);
extern void _SsContPanpot(short, short, unsigned char);
extern void _SsContExpression(short, short, unsigned char);
extern void _SsContDamper(short, short, unsigned char);
extern void _SsContExternal(short, short, unsigned char);
extern void _SsContNrpn1(short, short, unsigned char);
extern void _SsContNrpn2(short, short, unsigned char);
extern void _SsContRpn1(short, short, unsigned char);
extern void _SsContRpn2(short, short, unsigned char);
extern void _SsContResetAll(short, short);
extern void _SsSetNrpnVabAttr0(short, short, short, VagAtr, short, unsigned char);
extern void _SsSetNrpnVabAttr1(short, short, short, VagAtr, short, unsigned char);
extern void _SsSetNrpnVabAttr2(short, short, short, VagAtr, short, unsigned char);
extern void _SsSetNrpnVabAttr3(short, short, short, VagAtr, short, unsigned char);
extern void _SsSetNrpnVabAttr4(short, short, short, VagAtr, short, unsigned char);
extern void _SsSetNrpnVabAttr5(short, short, short, VagAtr, short, unsigned char);
extern void _SsSetNrpnVabAttr6(short, short, short, VagAtr, short, unsigned char);
extern void _SsSetNrpnVabAttr7(short, short, short, VagAtr, short, unsigned char);
extern void _SsSetNrpnVabAttr8(short, short, short, VagAtr, short, unsigned char);
extern void _SsSetNrpnVabAttr9(short, short, short, VagAtr, short, unsigned char);
extern void _SsSetNrpnVabAttr10(short, short, short, VagAtr, short, unsigned char);
extern void _SsSetNrpnVabAttr11(short, short, short, VagAtr, short, unsigned char);
extern void _SsSetNrpnVabAttr12(short, short, short, VagAtr, short, unsigned char);
extern void _SsSetNrpnVabAttr13(short, short, short, VagAtr, short, unsigned char);
extern void _SsSetNrpnVabAttr14(short, short, short, VagAtr, short, unsigned char);
extern void _SsSetNrpnVabAttr15(short, short, short, VagAtr, short, unsigned char);
extern void _SsSetNrpnVabAttr16(short, short, short, VagAtr, short, unsigned char);
extern void _SsSetNrpnVabAttr17(short, short, short, VagAtr, short, unsigned char);
extern void _SsSetNrpnVabAttr18(short, short, short, VagAtr, short, unsigned char);
extern void _SsSetNrpnVabAttr19(short, short, short, VagAtr, short, unsigned char);
extern void dmy_nothing1(short, short, unsigned char, unsigned char);
extern void dmy_SsNoteOn(short, short, unsigned char, unsigned char);
extern void dmy_SsSetProgramChange(short, short, unsigned char);
extern void dmy_SsGetMetaEvent(short, short, unsigned char);
extern void dmy_SsSetPitchBend(short, short);
extern void dmy_SsSetControlChange(short, short, unsigned char);
extern void dmy_SsContBankChange(short, short);
extern void dmy_SsContDataEntry(short, short, unsigned char);
extern void dmy_SsContMainVol(short, short, unsigned char);
extern void dmy_SsContPanpot(short, short, unsigned char);
extern void dmy_SsContExpression(short, short, unsigned char);
extern void dmy_SsContDamper(short, short, unsigned char);
extern void dmy_SsContExternal(short, short, unsigned char);
extern void dmy_SsContNrpn1(short, short, unsigned char);
extern void dmy_SsContNrpn2(short, short, unsigned char);
extern void dmy_SsContRpn1(short, short, unsigned char);
extern void dmy_SsContRpn2(short, short, unsigned char);
extern void dmy_SsContResetAll(short, short);
extern void dmy_SsSetNrpnVabAttr0(short, short, short, VagAtr, short, unsigned char);
extern void dmy_SsSetNrpnVabAttr1(short, short, short, VagAtr, short, unsigned char);
extern void dmy_SsSetNrpnVabAttr2(short, short, short, VagAtr, short, unsigned char);
extern void dmy_SsSetNrpnVabAttr3(short, short, short, VagAtr, short, unsigned char);
extern void dmy_SsSetNrpnVabAttr4(short, short, short, VagAtr, short, unsigned char);
extern void dmy_SsSetNrpnVabAttr5(short, short, short, VagAtr, short, unsigned char);
extern void dmy_SsSetNrpnVabAttr6(short, short, short, VagAtr, short, unsigned char);
extern void dmy_SsSetNrpnVabAttr7(short, short, short, VagAtr, short, unsigned char);
extern void dmy_SsSetNrpnVabAttr8(short, short, short, VagAtr, short, unsigned char);
extern void dmy_SsSetNrpnVabAttr9(short, short, short, VagAtr, short, unsigned char);
extern void dmy_SsSetNrpnVabAttr10(short, short, short, VagAtr, short, unsigned char);
extern void dmy_SsSetNrpnVabAttr11(short, short, short, VagAtr, short, unsigned char);
extern void dmy_SsSetNrpnVabAttr12(short, short, short, VagAtr, short, unsigned char);
extern void dmy_SsSetNrpnVabAttr13(short, short, short, VagAtr, short, unsigned char);
extern void dmy_SsSetNrpnVabAttr14(short, short, short, VagAtr, short, unsigned char);
extern void dmy_SsSetNrpnVabAttr15(short, short, short, VagAtr, short, unsigned char);
extern void dmy_SsSetNrpnVabAttr16(short, short, short, VagAtr, short, unsigned char);
extern void dmy_SsSetNrpnVabAttr17(short, short, short, VagAtr, short, unsigned char);
extern void dmy_SsSetNrpnVabAttr18(short, short, short, VagAtr, short, unsigned char);
extern void dmy_SsSetNrpnVabAttr19(short, short, short, VagAtr, short, unsigned char);
extern _SsFCALL SsFCALL;
typedef struct 
{
  short left;
  short right;
} SpuVolume;
typedef struct 
{
  unsigned long voice;
  unsigned long mask;
  SpuVolume volume;
  SpuVolume volmode;
  SpuVolume volumex;
  unsigned short pitch;
  unsigned short note;
  unsigned short sample_note;
  short envx;
  unsigned long addr;
  unsigned long loop_addr;
  long a_mode;
  long s_mode;
  long r_mode;
  unsigned short ar;
  unsigned short dr;
  unsigned short sr;
  unsigned short rr;
  unsigned short sl;
  unsigned short adsr1;
  unsigned short adsr2;
} SpuVoiceAttr;
typedef struct 
{
  unsigned long mask;
  long mode;
  SpuVolume depth;
  long delay;
  long feedback;
} SpuReverbAttr;
typedef struct 
{
  short cd_left[0x200];
  short cd_right[0x200];
  short voice1[0x200];
  short voice3[0x200];
} SpuDecodedData;
typedef SpuDecodedData SpuDecodeData;
typedef struct 
{
  SpuVolume volume;
  long reverb;
  long mix;
} SpuExtAttr;
typedef struct 
{
  unsigned long mask;
  SpuVolume mvol;
  SpuVolume mvolmode;
  SpuVolume mvolx;
  SpuExtAttr cd;
  SpuExtAttr ext;
} SpuCommonAttr;
typedef void (*SpuIRQCallbackProc)(void);
typedef void (*SpuTransferCallbackProc)(void);
typedef struct 
{
  unsigned long mask;
  unsigned long queueing;
} SpuEnv;
extern void SpuInit(void);
extern void SpuInitHot(void);
extern void SpuStart(void);
extern void SpuQuit(void);
extern long SpuSetMute(long on_off);
extern long SpuGetMute(void);
extern void SpuSetEnv(SpuEnv *env);
extern long SpuSetNoiseClock(long n_clock);
extern long SpuGetNoiseClock(void);
extern unsigned long SpuSetNoiseVoice(long on_off, unsigned long voice_bit);
extern unsigned long SpuGetNoiseVoice(void);
extern long SpuSetReverb(long on_off);
extern long SpuGetReverb(void);
extern long SpuSetReverbModeParam(SpuReverbAttr *attr);
extern void SpuGetReverbModeParam(SpuReverbAttr *attr);
extern long SpuSetReverbDepth(SpuReverbAttr *attr);
extern long SpuReserveReverbWorkArea(long on_off);
extern long SpuIsReverbWorkAreaReserved(long on_off);
extern unsigned long SpuSetReverbVoice(long on_off, unsigned long voice_bit);
extern unsigned long SpuGetReverbVoice(void);
extern long SpuClearReverbWorkArea(long mode);
extern unsigned long SpuWrite(unsigned char *addr, unsigned long size);
extern unsigned long SpuWrite0(unsigned long size);
extern unsigned long SpuRead(unsigned char *addr, unsigned long size);
extern long SpuSetTransferMode(long mode);
extern long SpuGetTransferMode(void);
extern unsigned long SpuSetTransferStartAddr(unsigned long addr);
extern unsigned long SpuGetTransferStartAddr(void);
extern unsigned long SpuWritePartly(unsigned char *addr, unsigned long size);
extern long SpuIsTransferCompleted(long flag);
extern SpuTransferCallbackProc SpuSetTransferCallback(SpuTransferCallbackProc func);
extern long SpuReadDecodedData(SpuDecodedData *d_data, long flag);
extern long SpuSetIRQ(long on_off);
extern long SpuGetIRQ(void);
extern unsigned long SpuSetIRQAddr(unsigned long);
extern unsigned long SpuGetIRQAddr(void);
extern SpuIRQCallbackProc SpuSetIRQCallback(SpuIRQCallbackProc);
extern void SpuSetVoiceAttr(SpuVoiceAttr *arg);
extern void SpuGetVoiceAttr(SpuVoiceAttr *arg);
extern void SpuSetKey(long on_off, unsigned long voice_bit);
extern void SpuSetKeyOnWithAttr(SpuVoiceAttr *attr);
extern long SpuGetKeyStatus(unsigned long voice_bit);
extern void SpuGetAllKeysStatus(char *status);
extern unsigned long SpuFlush(unsigned long ev);
extern unsigned long SpuSetPitchLFOVoice(long on_off, unsigned long voice_bit);
extern unsigned long SpuGetPitchLFOVoice(void);
extern void SpuSetCommonAttr(SpuCommonAttr *attr);
extern void SpuGetCommonAttr(SpuCommonAttr *attr);
extern long SpuInitMalloc(long num, char *top);
extern long SpuMalloc(long size);
extern long SpuMallocWithStartAddr(unsigned long addr, long size);
extern void SpuFree(unsigned long addr);
extern long SpuRGetAllKeysStatus(long min_, long max_, char *status);
extern long SpuRSetVoiceAttr(long min_, long max_, SpuVoiceAttr *arg);
extern void SpuNSetVoiceAttr(int vNum, SpuVoiceAttr *arg);
extern void SpuNGetVoiceAttr(int vNum, SpuVoiceAttr *arg);
extern void SpuSetVoiceVolume(int vNum, short volL, short volR);
extern void SpuSetVoiceVolumeAttr(int vNum, short volL, short volR, short volModeL, short volModeR);
extern void SpuSetVoicePitch(int vNum, unsigned short pitch);
extern void SpuSetVoiceNote(int vNum, unsigned short note);
extern void SpuSetVoiceSampleNote(int vNum, unsigned short sampleNote);
extern void SpuSetVoiceStartAddr(int vNum, unsigned long startAddr);
extern void SpuSetVoiceLoopStartAddr(int vNum, unsigned long lsa);
extern void SpuSetVoiceAR(int vNum, unsigned short AR);
extern void SpuSetVoiceDR(int vNum, unsigned short DR);
extern void SpuSetVoiceSR(int vNum, unsigned short SR);
extern void SpuSetVoiceRR(int vNum, unsigned short RR);
extern void SpuSetVoiceSL(int vNum, unsigned short SL);
extern void SpuSetVoiceARAttr(int vNum, unsigned short AR, long ARmode);
extern void SpuSetVoiceSRAttr(int vNum, unsigned short SR, long SRmode);
extern void SpuSetVoiceRRAttr(int vNum, unsigned short RR, long RRmode);
extern void SpuSetVoiceADSR(int vNum, unsigned short AR, unsigned short DR, unsigned short SR, unsigned short RR, unsigned short SL);
extern void SpuSetVoiceADSRAttr(int vNum, unsigned short AR, unsigned short DR, unsigned short SR, unsigned short RR, unsigned short SL, long ARmode, long SRmode, long RRmode);
extern void SpuGetVoiceVolume(int vNum, short *volL, short *volR);
extern void SpuGetVoiceVolumeAttr(int vNum, short *volL, short *volR, short *volModeL, short *volModeR);
extern void SpuGetVoiceVolumeX(int vNum, short *volXL, short *volXR);
extern void SpuGetVoicePitch(int vNum, unsigned short *pitch);
extern void SpuGetVoiceNote(int vNum, unsigned short *note);
extern void SpuGetVoiceSampleNote(int vNum, unsigned short *sampleNote);
extern void SpuGetVoiceEnvelope(int vNum, short *envx);
extern void SpuGetVoiceStartAddr(int vNum, unsigned long *startAddr);
extern void SpuGetVoiceLoopStartAddr(int vNum, unsigned long *loopStartAddr);
extern void SpuGetVoiceAR(int vNum, unsigned short *AR);
extern void SpuGetVoiceDR(int vNum, unsigned short *DR);
extern void SpuGetVoiceSR(int vNum, unsigned short *SR);
extern void SpuGetVoiceRR(int vNum, unsigned short *RR);
extern void SpuGetVoiceSL(int vNum, unsigned short *SL);
extern void SpuGetVoiceARAttr(int vNum, unsigned short *AR, long *ARmode);
extern void SpuGetVoiceSRAttr(int vNum, unsigned short *SR, long *SRmode);
extern void SpuGetVoiceRRAttr(int vNum, unsigned short *RR, long *RRmode);
extern void SpuGetVoiceADSR(int vNum, unsigned short *AR, unsigned short *DR, unsigned short *SR, unsigned short *RR, unsigned short *SL);
extern void SpuGetVoiceADSRAttr(int vNum, unsigned short *AR, unsigned short *DR, unsigned short *SR, unsigned short *RR, unsigned short *SL, long *ARmode, long *SRmode, long *RRmode);
extern void SpuGetVoiceEnvelopeAttr(int vNum, long *keyStat, short *envx);
extern void SpuSetCommonMasterVolume(short mvol_left, short mvol_right);
extern void SpuSetCommonMasterVolumeAttr(short mvol_left, short mvol_right, short mvolmode_left, short mvolmode_right);
extern void SpuSetCommonCDMix(long cd_mix);
extern void SpuSetCommonCDVolume(short cd_left, short cd_right);
extern void SpuSetCommonCDReverb(long cd_reverb);
extern void SpuGetCommonMasterVolume(short *mvol_left, short *mvol_right);
extern void SpuGetCommonMasterVolumeX(short *mvolx_left, short *mvolx_right);
extern void SpuGetCommonMasterVolumeAttr(short *mvol_left, short *mvol_right, short *mvolmode_left, short *mvolmode_right);
extern void SpuGetCommonCDMix(long *cd_mix);
extern void SpuGetCommonCDVolume(short *cd_left, short *cd_right);
extern void SpuGetCommonCDReverb(long *cd_reverb);
extern long SpuSetReverbModeType(long mode);
extern void SpuSetReverbModeDepth(short depth_left, short depth_right);
extern void SpuSetReverbModeDelayTime(long delay);
extern void SpuSetReverbModeFeedback(long feedback);
extern void SpuGetReverbModeType(long *mode);
extern void SpuGetReverbModeDepth(short *depth_left, short *depth_right);
extern void SpuGetReverbModeDelayTime(long *delay);
extern void SpuGetReverbModeFeedback(long *feedback);
typedef struct 
{
  char status;
  char pad1;
  char pad2;
  char pad3;
  long last_size;
  unsigned long buf_addr;
  unsigned long data_addr;
} SpuStVoiceAttr;
typedef struct 
{
  long size;
  long low_priority;
  SpuStVoiceAttr voice[24];
} SpuStEnv;
typedef void (*SpuStCallbackProc)(unsigned long, long);
extern SpuStEnv *SpuStInit(long);
extern long SpuStQuit(void);
extern long SpuStGetStatus(void);
extern unsigned long SpuStGetVoiceStatus(void);
extern long SpuStTransfer(long flag, unsigned long voice_bit);
extern SpuStCallbackProc SpuStSetPreparationFinishedCallback(SpuStCallbackProc func);
extern SpuStCallbackProc SpuStSetTransferFinishedCallback(SpuStCallbackProc func);
extern SpuStCallbackProc SpuStSetStreamFinishedCallback(SpuStCallbackProc func);
extern void *memcpy();
extern void *memmove(unsigned char *, unsigned char *, int);
extern int memcmp();
extern void *memchr(unsigned char *, unsigned char, int);
extern void *memset(unsigned char *, unsigned char, int);
extern void *bcopy(unsigned char *, unsigned char *, int);
extern void *bzero(unsigned char *, int);
extern int bcmp(unsigned char *, unsigned char *, int);
extern char *strcat(char *, char *);
extern char *strncat(char *, char *, int);
extern int strcmp();
extern int strncmp(char *, char *, int);
extern char *strcpy();
extern char *strncpy(char *, char *, int);
extern int strlen();
extern char *index(char *, char);
extern char *rindex(char *, char);
extern char *strchr(char *, char);
extern char *strrchr(char *, char);
extern char *strpbrk(char *, char *);
extern int strspn(char *, char *);
extern int strcspn(char *, char *);
extern char *strtok(char *, char *);
extern char *strstr(char *, char *);
typedef void (*CdlCB)(u_char, u_char *);
typedef struct 
{
  u_char minute;
  u_char second;
  u_char sector;
  u_char track;
} CdlLOC;
typedef struct 
{
  u_char file;
  u_char chan;
  u_short pad;
} CdlFILTER;
typedef struct 
{
  u_char val0;
  u_char val1;
  u_char val2;
  u_char val3;
} CdlATV;
typedef struct 
{
  CdlLOC pos;
  u_long size;
  char name[16];
} CdlFILE;
typedef struct 
{
  u_short id;
  u_short type;
  u_short secCount;
  u_short nSectors;
  u_long frameCount;
  u_long frameSize;
  u_short width;
  u_short height;
  u_long dummy1;
  u_long dummy2;
  CdlLOC loc;
} StHEADER;
void StSetRing(u_long *ring_addr, u_long ring_size);
void StClearRing(void);
void StUnSetRing(void);
void StSetStream(u_long mode, u_long start_frame, u_long end_frame, void (*func1)(), void (*func2)());
void StSetEmulate(u_long *addr, u_long mode, u_long start_frame, u_long end_frame, void (*func1)(), void (*func2)());
u_long StFreeRing(u_long *base);
u_long StGetNext(u_long **addr, u_long **header);
u_long StGetNextS(u_long **addr, u_long **header);
u_short StNextStatus(u_long **addr, u_long **header);
void StRingStatus(short *free_sectors, short *over_sectors);
void StSetMask(u_long mask, u_long start, u_long end);
void StCdInterrupt(void);
int StGetBackloc(CdlLOC *loc);
int StSetChannel(u_long channel);
void CdFlush(void);
CdlFILE *CdSearchFile(CdlFILE *fp, char *name);
CdlLOC *CdIntToPos(int i, CdlLOC *p);
char *CdComstr(u_char com);
char *CdIntstr(u_char intr);
int CdControl(u_char com, u_char *param, u_char *result);
int CdControlB(u_char com, u_char *param, u_char *result);
int CdControlF(u_char com, u_char *param);
int CdGetSector(void *madr, int size);
int CdGetSector2(void *madr, int size);
int CdDataSync(int mode);
int CdGetToc(CdlLOC *loc);
int CdPlay(int mode, int *track, int offset);
int CdMix(CdlATV *vol);
int CdPosToInt(CdlLOC *p);
int CdRead(int sectors, u_long *buf, int mode);
int CdRead2(long mode);
int CdReadFile(char *file, u_long *addr, int nbyte);
int CdReadSync(int mode, u_char *result);
int CdReady(int mode, u_char *result);
int CdSetDebug(int level);
int CdSync(int mode, u_char *result);
void *CdDataCallback(void (*func)());
CdlCB CdReadCallback(CdlCB func);
CdlCB CdReadyCallback(CdlCB func);
CdlCB CdSyncCallback(CdlCB func);
int CdInit(void);
int CdReset(int mode);
int CdStatus(void);
int CdLastCom(void);
CdlLOC *CdLastPos(void);
int CdMode(void);
int CdDiskReady(int mode);
int CdGetDiskType(void);
struct EXEC *CdReadExec(char *file);
void CdReadBreak(void);
int CdReadMode(int mode);
typedef char dw_bool;
typedef char int8_t;
typedef short int16_t;
typedef int int32_t;
typedef unsigned char uint8_t;
typedef unsigned short uint16_t;
typedef unsigned int uint32_t;
typedef struct 
{
  CdlLOC pos;
  uint32_t size;
  uint32_t unk2;
  uint32_t unk3;
  uint32_t unk4;
  uint32_t unk5;
} FileLookup;
int32_t lookupFileTable(FileLookup *lookup, char *path);
uint32_t lookupFileSize(char *path);
int32_t loadTextureFile(char *path, uint32_t *outTPage, uint32_t *outClut);
int32_t readFile(char *path, void *buffer);
int32_t loadTIMFile(char *path, void *buffer);
int32_t loadStackedTIMEntry(char *path, void *buffer, int32_t offset, int32_t sectors);
int32_t readFileSectors(char *path, void *buffer, int32_t offset, int32_t sectors);
extern uint8_t *GENERAL_BUFFER_PTR;
typedef struct 
{
  char name[20];
  int32_t boneCount;
  int16_t radius;
  int16_t height;
  uint8_t type;
  uint8_t level;
  uint8_t special[3];
  uint8_t dropItem;
  uint8_t dropChance;
  uint8_t moves[16];
  uint8_t padding;
} DigimonPara;
typedef struct 
{
  uint32_t condition;
  int16_t sleepyHour;
  int16_t sleepyMinute;
  int16_t wakeupHour;
  int16_t wakeupMinute;
  int16_t hoursAwakeDefault;
  int16_t hoursAsleepDefault;
  int16_t timeAwakeToday;
  int16_t sicknessCounter;
  int16_t missedSleepHours;
  int16_t tirednessSleepTimer;
  int16_t poopLevel;
  int16_t unused1;
  int16_t unused2;
  int16_t virusBar;
  int16_t poopingTimer;
  int16_t tiredness;
  int16_t subTiredness;
  int16_t tirednessHungerTimer;
  int16_t discipline;
  int16_t happiness;
  int16_t unused3;
  int16_t unused4;
  int16_t timesBeingSick;
  int16_t sicknessTries;
  int16_t areaEffectTimer;
  int16_t sicknessTimer;
  int16_t injuryTimer;
  int16_t nextHungerHour;
  int16_t energyLevel;
  int16_t foodLevel;
  int16_t starvationTimer;
  int16_t weight;
  int16_t refusedFavFood;
  int16_t emptyStomachTimer;
  int16_t remainingLifetime;
  int16_t age;
  uint16_t trainBoostFlag;
  uint16_t trainBoostValue;
  uint16_t trainBoostTimer;
  int16_t careMistakes;
  int16_t battles;
  int16_t evoTimer;
  int16_t unused5;
  int16_t unused6;
  int16_t unused7;
  int16_t fishCaught;
  int16_t unused8;
  int16_t unused9;
  int16_t unused10;
  int16_t upgradeHPcounter;
  int16_t upgradeMPcounter;
  int16_t upgradeOffCounter;
  int16_t buggedUpgradeBrainsCounter;
  int16_t upgradeDefenseCounter;
  int16_t upgradeSpeedCounter;
  int16_t upgradeBrainCounter;
  int16_t unused11;
  int16_t sukaBackupHP;
  int16_t sukaBackupMP;
  int16_t sukaBackupOff;
  int16_t sukaBackupDef;
  int16_t sukaBackupSpeed;
  int16_t sukaBackupBrain;
  int16_t unused12;
} PartnerPara;
extern DigimonPara DIGIMON_DATA[180];
extern PartnerPara PARTNER_PARA;
typedef struct 
{
  uint16_t sectorId;
  uint16_t sectorCount;
} MapSoundPara;
extern void *VHB_HEADER_ADDR[];
extern unsigned long VHB_SOUNDBUFFER_START[];
extern int32_t ACTIVE_MAP_SOUND_ID;
extern MapSoundPara MAP_SOUND_PARA[];
extern uint8_t DIGIMON_VBALL_SOUND_ID[];
extern uint8_t DIGIMON_VLALL_SOUND_ID[];
int32_t initializeMusic(void);
void finalizeMusic(void);
int32_t loadMapSounds(int32_t mapSoundId);
int32_t loadVSSounds(void);
int32_t loadDigimonSounds(int32_t vabId, int32_t type);
int32_t loadPartnerSounds(int32_t type);
uint32_t playSound(int32_t vabId, int32_t val);
uint32_t playSound2(int32_t vabId, int32_t val);
void stopSound(void);
void stopSoundMask(uint32_t mask);
int32_t playMusic(int32_t font, int32_t track);
void stopBGM(void);
uint8_t VHB_HEADER_SS[0x1000];
uint8_t VHB_HEADER_SL[0x1000];
uint8_t VHB_HEADER_FAALL[0x2000];
uint8_t VHB_HEADER_VLALL[0x1000];
uint8_t VHB_HEADER_VBALL_0[0x1000];
uint8_t VHB_HEADER_VBALL_1[0x1000];
uint8_t VHB_HEADER_VBALL_2[0x1000];
uint8_t VHB_HEADER_VBALL_3[0x1000];
uint8_t VHB_HEADER_ESALL_SB[0x1800];
void *VHB_HEADER_ADDR[10] = {VHB_HEADER_SS, VHB_HEADER_SL, VHB_HEADER_FAALL, VHB_HEADER_VLALL, VHB_HEADER_VBALL_0, VHB_HEADER_VBALL_1, VHB_HEADER_VBALL_2, VHB_HEADER_VBALL_3, VHB_HEADER_ESALL_SB, 0};
unsigned long VHB_SOUNDBUFFER_START[10] = {0x1010, 0xe800, 0x1b800, 0x2a000, 0x31800, 0x34000, 0x36800, 0x39000, 0x3b800, 0x0};
uint8_t DIGIMON_VLALL_SOUND_ID[66] = {0x00, 0x00, 0x00, 0x01, 0x01, 0x02, 0x03, 0x04, 0x02, 0x0b, 0x05, 0x06, 0x0a, 0x00, 0x0f, 0x00, 0x00, 0x01, 0x01, 0x08, 0x0b, 0x04, 0x07, 0x03, 0x05, 0x0e, 0x02, 0x00, 0x0a, 0x00, 0x00, 0x01, 0x01, 0x09, 0x03, 0x06, 0x09, 0x00, 0x07, 0x06, 0x0a, 0x0a, 0x0c, 0x00, 0x00, 0x01, 0x01, 0x07, 0x03, 0x05, 0x04, 0x08, 0x03, 0x03, 0x02, 0x00, 0x01, 0x01, 0x00, 0x04, 0x08, 0x05, 0x07, 0x03, 0x02, 0x0c};
uint8_t DIGIMON_VBALL_SOUND_ID[180] = {0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x01, 0x02, 0x0f, 0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1a, 0x01, 0x02, 0x1b, 0x1c, 0x1d, 0x1e, 0x1f, 0x20, 0x21, 0x22, 0x23, 0x24, 0x25, 0x26, 0x01, 0x02, 0x27, 0x28, 0x29, 0x2a, 0x2b, 0x2c, 0x2d, 0x2e, 0x2f, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x00, 0x2a, 0x30, 0x26, 0x38, 0x39, 0x3a, 0x3b, 0x3c, 0x03, 0x1e, 0x23, 0x1c, 0x1d, 0x3d, 0x3e, 0x3f, 0x22, 0x40, 0x41, 0x0f, 0x04, 0x03, 0x12, 0x28, 0x0b, 0x29, 0x1e, 0x25, 0x1f, 0x24, 0x33, 0x3a, 0x2c, 0x1b, 0x40, 0x03, 0x17, 0x06, 0x3b, 0x39, 0x40, 0x09, 0x14, 0x13, 0x21, 0x15, 0x42, 0x43, 0x44, 0x45, 0x3a, 0x46, 0x30, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f, 0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1a, 0x1b, 0x1c, 0x1d, 0x1e, 0x1f, 0x20, 0x21, 0x22, 0x23, 0x24, 0x25, 0x26, 0x27, 0x28, 0x29, 0x2a, 0x2b, 0x2c, 0x2d, 0x2e, 0x2f, 0x30, 0x31, 0x32, 0x34, 0x33, 0x38, 0x05, 0x0c};
MapSoundPara MAP_SOUND_PARA[22] = {{0x0000, 0x00e8}, {0x00e8, 0x0064}, {0x014c, 0x00de}, {0x022a, 0x004c}, {0x0276, 0x00f8}, {0x036e, 0x00e6}, {0x0454, 0x00ee}, {0x0542, 0x0046}, {0x0588, 0x00de}, {0x0666, 0x0086}, {0x06ec, 0x0038}, {0x0724, 0x00f8}, {0x081c, 0x00ee}, {0x090a, 0x00a4}, {0x09ae, 0x009e}, {0x0a4c, 0x0062}, {0x0aae, 0x0062}, {0x0b10, 0x00b2}, {0x0bc2, 0x003e}, {0x0c00, 0x00bc}, {0x0cbc, 0x007e}, {0x0d3a, 0x00e2}};
int32_t FREE_CHANNEL_INDEX;
int16_t SEQ_ACCESS_NUM;
int16_t CURRENT_SEQ_FONT;
int16_t CURRENT_SEQ_TRACK;
char SEQ_TABLE[0xb0];
uint8_t SEQ_BUFFER[0x5678];
char VHB_EXT[] = ".VHB";
int32_t ACTIVE_MAP_SOUND_ID = -1;
int32_t readVHBFile(int32_t vabId, char *filename, uint8_t *buffer);
int32_t readVHBFileSectors(int32_t vabId, char *filename, uint8_t *buffer, uint32_t offset, int32_t sectors);
int32_t loadMusicFont(int32_t font);
uint32_t getNextFreeChannel(int32_t arg);
uint32_t startSound(int32_t vabId, char prog, char note);
void seqOpen(void);
void seqPlay(void);
void seqStop(void);
void seqClose(void);
void concatStrings3(char *dst, char *src1, char *src2);
void _stopSoundMask(uint32_t mask);
static void *sound_functions[] = {concatStrings3, loadMusicFont, seqPlay, seqOpen, readVHBFileSectors, seqClose, seqStop, readVHBFile};
static void *sound_bss[] = {SEQ_BUFFER, SEQ_TABLE, &CURRENT_SEQ_TRACK, &CURRENT_SEQ_FONT, &SEQ_ACCESS_NUM, &FREE_CHANNEL_INDEX};
int32_t readVHBFile(int32_t vabId, char *filename, uint8_t *buffer);
void seqStop(void);
void seqClose(void);
int32_t readVHBFileSectors(int32_t vabId, char *filename, uint8_t *buffer, uint32_t offset, int32_t sectors);
void seqOpen(void);
void seqPlay(void);
void concatStrings3(char *dst, char *src1, char *src2);
int32_t initializeMusic(void);
void finalizeMusic(void);
uint32_t getNextFreeChannel(int32_t arg);
inline char *inline_fn(char *arg0, char arg1)
{
  return arg0 + (arg1 << 9);
}

uint32_t startSound(int32_t vabId, char prog, char note)
{
  int32_t mask;
  char *tones;
  unsigned int chan;
  int16_t i;
  int32_t ofs;
  mask = 0;
  tones = ((char *) VHB_HEADER_ADDR[vabId]) + 0x820;
  tones = inline_fn(tones, prog);
  chan = 0x18;
  for (i = 0, ofs = 0; i < 0x10; i++, ofs += 0x20)
  {
    if (note == (*((tones + ofs) + 7)))
    {
      chan = getNextFreeChannel(chan);
      mask = -1;
      if (chan == mask)
      {
        break;
      }
      SsUtKeyOnV(chan, vabId, prog, (0, i ^ 0), note, (i < 0x10) * 0, 0x7F, 0x7F);
      mask |= 1 << chan;
    }
  }

  return mask;
}

void _stopSoundMask(uint32_t mask);
uint32_t playSound(int32_t vabId, int32_t val);
void stopSound(void);
uint32_t playSound2(int32_t vabId, int32_t val);
void stopSoundMask(uint32_t mask);
int32_t loadPartnerSounds(int32_t type);
int32_t loadDigimonSounds(int32_t vabId, int32_t type);
int32_t loadVSSounds(void);
int32_t loadMapSounds(int32_t mapSoundId);
int32_t loadMusicFont(int32_t font);
int32_t playMusic(int32_t font, int32_t track);
void stopBGM(void);
