#ifndef DW_VERSION_H
#define DW_VERSION_H

/* Build dates of the main executables */
#define VERSION_DATE_JP		19981224
#define VERSION_DATE_JP_TRIAL	19990118
#define VERSION_DATE_JP_BOMBOM	19990122
#define VERSION_DATE_US		19990331
#define VERSION_DATE_JP_REV1	19990406
#define VERSION_DATE_EU		20010504

#define VERSION_ID_JP		1
#define VERSION_ID_JP_TRIAL	2
#define VERSION_ID_JP_BOMBOM	3
#define VERSION_ID_US		4
#define VERSION_ID_JP_REV1	5
#define VERSION_ID_EU		6

#define VERSION_REGION_NTSCJ	1
#define VERSION_REGION_NTSCU	2
#define VERSION_REGION_PAL	3

#if defined(VERSION_JP)
#define VERSION_ID		VERSION_ID_JP
#define VERSION_DATE		VERSION_DATE_JP
#define VERSION_REGION		VERSION_REGION_NTSCJ
#elif defined(VERSION_JP_TRIAL)
#define VERSION_ID		VERSION_ID_JP_TRIAL
#define VERSION_DATE		VERSION_DATE_JP_TRIAL
#define VERSION_REGION		VERSION_REGION_NTSCJ
#elif defined(VERSION_JP_BOMBOM)
#define VERSION_ID		VERSION_ID_JP_BOMBOM
#define VERSION_DATE		VERSION_DATE_JP_BOMBOM
#define VERSION_REGION		VERSION_REGION_NTSCJ
#elif defined(VERSION_US)
#define VERSION_ID		VERSION_ID_US
#define VERSION_DATE		VERSION_DATE_US
#define VERSION_REGION		VERSION_REGION_NTSCU
#elif defined(VERSION_JP_REV1)
#define VERSION_ID		VERSION_ID_JP_REV1
#define VERSION_DATE		VERSION_DATE_JP_REV1
#define VERSION_REGION		VERSION_REGION_NTSCJ
#elif defined(VERSION_EU)
#define VERSION_ID		VERSION_ID_EU
#define VERSION_DATE		VERSION_DATE_EU
#define VERSION_REGION		VERSION_REGION_PAL
#else
#error "unknown version"
#endif

#define VERSION_IS(v)			(VERSION_ID == VERSION_ID_##v)
#define VERSION_REGION_IS(r)		(VERSION_REGION == VERSION_REGION_##r)
#define VERSION_EQUAL_OR_NEWER(v)	(VERSION_DATE >= VERSION_DATE_##v)
#define VERSION_EQUAL_OR_OLDER(v)	(VERSION_DATE <= VERSION_DATE_##v)

#endif
