name: build
on:
  push:
  pull_request_target:
  workflow_dispatch:
permissions:
  contents: read
  packages: read
jobs:
  build:
    if: github.repository == 'jype0/dw_decomp'
    strategy:
      fail-fast: false
      matrix:
        version: ["jp", "jp_trial", "jp_bombom", "us", "jp_rev1", "eu"]
    env:
      VERSION: ${{ matrix.version }}
    container:
      image: ghcr.io/jype0/dw-build:latest
      options: --user root
      volumes:
        - dw_venv:/dw/.venv
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        ref: ${{ github.event.pull_request.head.sha || github.ref }}
        submodules: recursive
        persist-credentials: false
        allow-unsafe-pr-checkout: true

    - uses: actions/checkout@v5
      with:
        repository: jype0/dw_decomp_dependencies
        token: ${{ secrets.DW_DECOMP_DEPENDENCIES_TOKEN }}
        path: tmp
        persist-credentials: false

    - run: |
        mkdir -p disks
        cat tmp/dw* > tmp/dw.tar.gz
        tar -xf tmp/dw.tar.gz -C disks/
        mkdir -p bin/cc_mips
        cat tmp/cc_mips* > tmp/cc_mips.tar.gz
        tar -xf tmp/cc_mips.tar.gz -C bin/cc_mips/
        rm -rf tmp
    - run: tools/dl_deps.sh
    - name: Build and compare matching binaries
      run: |
        make -j$(nproc) generate
        make -j$(nproc)
        make compare
    - if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: make report
    - if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: actions/upload-artifact@v5
      with:
        name: ${{ matrix.version }}_report
        path: build/${{ matrix.version }}/psx/mwcc/report.json
    - name: Build gcc binaries
      run: make -j$(nproc) TOOLCHAIN=gcc
